[package]
name = "bow"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.23", features = ["blocking"] }
serde = "1.0.228"
serde_yaml_bw = "2.4.1"
strum = { version = "0.27.2", features = ["derive"] }
tempfile = "3.23.0"
